"""Live (editable) Photoshop structures for the CL2K PSD export.

Builds the pieces that make the exported ``.psd`` genuinely editable in
Photoshop/Photopea instead of a stack of rasters: the BORDER LAYER's live
Stroke + Inner Glow effects (``lfx2``), the live black gradient fill layer
(``GdFl``), and a real type layer (``TySh``) for the bottom label.

The effect and gradient descriptors are constructed from scratch, from the
values extracted out of the community CL2K template (see the constants below —
they are format facts, the same ones geometry.py records). The type layer's
text-engine data is the one structure too risky to hand-build (Photoshop
rejects malformed EngineData), so it is transplanted from a committed donor
block (``assets/cl2k/label_tysh.bin``, generated by
``scripts/gen_cl2k_label_tysh.py``) and re-texted per export.

psd-tools' own compositor cannot render these effects (Inner Glow is
unimplemented; its stroke painter breaks at canvas edges), so exports must
inject the faithful flat render as the embedded preview via
:func:`inject_preview` and NEVER let ``PSDImage.save()`` recomposite — it
would embed garbage for every non-Photoshop viewer.
"""

from __future__ import annotations

import copy
import io
import logging
from typing import Any, Optional

from backend.util.cl2k import geometry as geo

# The values Photoshop stores for the CL2K border effects and gradient fill,
# read from the community template's own descriptors. Stroke: 25px Inside,
# white, 100%. Inner glow: multiply black 70%, Softer, choke 50, size 45,
# range 50%, source Edge. Gradient: linear 90deg, scale 30%, offset
# (-19.2%, 32.71328125%), opacity stops 100%@819/4096 and 0%@3909/4096.
_GLOW_OPACITY = 70.0
_GLOW_CHOKE = 50.0
_GLOW_SIZE = 45.0
_GLOW_RANGE = 50.0
_GRAD_SCALE = 30.0
_GRAD_OFFSET = (-19.2, 32.71328125)
_GRAD_STOP_FULL = 819  # of 4096 — the opacity-100% stop (y=1375.72 on canvas)
_GRAD_STOP_ZERO = 3909  # the opacity-0% stop (y=1036.24 on canvas)

# The label baseline Photoshop anchors type at, per band (measured off finished
# creator PSDs; geometry's *_Y values are ink centres, these are baselines).
_TYPE_BASELINE = {geo.SEASON_TEXT_Y: 1451.0, geo.COLLECTION_LABEL_Y: 1360.5}

LABEL_TYSH_BIN = geo.ASSET_DIR / "label_tysh.bin"


def _d(class_id: bytes, items, name: str = "") -> Any:
    from psd_tools.psd.descriptor import Descriptor

    desc = Descriptor(name=name, classID=class_id)
    for key, value in items:
        desc[key] = value
    return desc


def _rgb(r: float, g: float, b: float) -> Any:
    from psd_tools.psd.descriptor import Double

    return _d(b"RGBC", [(b"Rd  ", Double(r)), (b"Grn ", Double(g)), (b"Bl  ", Double(b))])


def border_effects_block() -> Any:
    """The BORDER LAYER's ``lfx2`` tagged block: live Stroke + Inner Glow.

    Minimal 5-key form (the template itself ships exactly this set and renders
    correctly in Photoshop). Every effect sub-descriptor MUST carry
    ``present=True`` — without it Photoshop/psd-tools treat the effect as
    absent even with ``enab=True``.
    """
    from psd_tools.constants import Tag
    from psd_tools.psd.descriptor import Bool, Double, Enumerated, Integer, List, String, UnitFloat
    from psd_tools.psd.tagged_blocks import DescriptorBlock2, TaggedBlock
    from psd_tools.terminology import Unit

    stroke = _d(
        b"FrFX",
        [
            (b"enab", Bool(True)),
            (b"present", Bool(True)),
            (b"showInDialog", Bool(True)),
            (b"Styl", Enumerated(typeID=b"FStl", enum=b"InsF")),  # Inside
            (b"PntT", Enumerated(typeID=b"FrFl", enum=b"SClr")),  # solid colour
            (b"Md  ", Enumerated(typeID=b"BlnM", enum=b"Nrml")),
            (b"Opct", UnitFloat(value=100.0, unit=Unit.Percent)),
            (b"Sz  ", UnitFloat(value=float(geo.BORDER_WIDTH), unit=Unit.Pixels)),
            (b"Clr ", _rgb(255.0, 255.0, 255.0)),
            (b"overprint", Bool(False)),
        ],
    )
    curve = List()
    for x, y in ((0.0, 0.0), (255.0, 255.0)):
        curve.append(_d(b"CrPt", [(b"Hrzn", Double(x)), (b"Vrtc", Double(y))]))
    contour = _d(b"ShpC", [(b"Nm  ", String("Linear")), (b"Crv ", curve)])
    glow = _d(
        b"IrGl",
        [
            (b"enab", Bool(True)),
            (b"present", Bool(True)),
            (b"showInDialog", Bool(True)),
            (b"Md  ", Enumerated(typeID=b"BlnM", enum=b"Mltp")),
            (b"Clr ", _rgb(0.0, 0.0, 0.0)),
            (b"Opct", UnitFloat(value=_GLOW_OPACITY, unit=Unit.Percent)),
            (b"GlwT", Enumerated(typeID=b"BETE", enum=b"SfBL")),  # Softer
            (b"Ckmt", UnitFloat(value=_GLOW_CHOKE, unit=Unit.Pixels)),
            (b"blur", UnitFloat(value=_GLOW_SIZE, unit=Unit.Pixels)),
            (b"Nose", UnitFloat(value=0.0, unit=Unit.Percent)),
            (b"ShdN", UnitFloat(value=0.0, unit=Unit.Percent)),
            (b"AntA", Bool(False)),
            (b"TrnS", contour),
            (b"Inpr", UnitFloat(value=_GLOW_RANGE, unit=Unit.Percent)),
            (b"glwS", Enumerated(typeID=b"IGSr", enum=b"SrcE")),  # from Edge
        ],
    )
    root = _d(
        b"null",
        [
            (b"Scl ", UnitFloat(value=100.0, unit=Unit.Percent)),
            (b"masterFXSwitch", Bool(True)),
            (b"numModifyingFX", Integer(2)),
            (b"FrFX", stroke),
            (b"IrGl", glow),
        ],
    )
    data = DescriptorBlock2(name=root.name, classID=root.classID, version=0, data_version=16)
    for key, value in root.items():
        data[key] = value
    return TaggedBlock(key=Tag.OBJECT_BASED_EFFECTS_LAYER_INFO.value, data=data)


def gradient_fill_block() -> Any:
    """The GRADIENT layer's live ``GdFl`` fill descriptor.

    Photoshop rasterises this to exactly the template's ramp (the baked
    ``gradient.png`` matches the descriptor's own maths to <2px on the stop
    positions), so the live layer and the flat render agree.
    """
    from psd_tools.constants import Tag
    from psd_tools.psd.descriptor import Bool, Double, Enumerated, Integer, List, String, UnitFloat
    from psd_tools.psd.tagged_blocks import DescriptorBlock, TaggedBlock
    from psd_tools.terminology import Unit

    colors = List()
    for location in (0, 4096):
        colors.append(
            _d(
                b"Clrt",
                [
                    (b"Clr ", _rgb(0.0, 0.0, 0.0)),
                    (b"Type", Enumerated(typeID=b"Clry", enum=b"UsrS")),
                    (b"Lctn", Integer(location)),
                    (b"Mdpn", Integer(50)),
                ],
            )
        )
    opacities = List()
    for opacity, location, midpoint in (
        (100.0, _GRAD_STOP_FULL, 50),
        (0.0, _GRAD_STOP_ZERO, 70),
    ):
        opacities.append(
            _d(
                b"TrnS",
                [
                    (b"Opct", UnitFloat(value=opacity, unit=Unit.Percent)),
                    (b"Lctn", Integer(location)),
                    (b"Mdpn", Integer(midpoint)),
                ],
            )
        )
    gradient = _d(
        b"Grdn",
        [
            (b"Nm  ", String("Custom")),
            (b"GrdF", Enumerated(typeID=b"GrdF", enum=b"CstS")),
            (b"Intr", Double(4096.0)),
            (b"Clrs", colors),
            (b"Trns", opacities),
        ],
        name="Gradient",
    )
    root = _d(
        b"null",
        [
            (b"Dthr", Bool(True)),
            (
                b"gradientsInterpolationMethod",
                Enumerated(typeID=b"gradientInterpolationMethodType", enum=b"Gcls"),
            ),
            (b"Angl", UnitFloat(value=90.0, unit=Unit.Angle)),
            (b"Type", Enumerated(typeID=b"GrdT", enum=b"Lnr ")),
            (b"Algn", Bool(False)),
            (b"Scl ", UnitFloat(value=_GRAD_SCALE, unit=Unit.Percent)),
            (
                b"Ofst",
                _d(
                    b"Pnt ",
                    [
                        (b"Hrzn", UnitFloat(value=_GRAD_OFFSET[0], unit=Unit.Percent)),
                        (b"Vrtc", UnitFloat(value=_GRAD_OFFSET[1], unit=Unit.Percent)),
                    ],
                ),
            ),
            (b"Grad", gradient),
            (b"Rvrs", Bool(False)),
        ],
    )
    data = DescriptorBlock(name=root.name, classID=root.classID, version=16)
    for key, value in root.items():
        data[key] = value
    return TaggedBlock(key=Tag.GRADIENT_FILL_SETTING.value, data=data)


def label_type_block(
    text: str, tracking: int, label_center_y: int, ink_width: float
) -> Optional[Any]:
    """A ``TySh`` block reading ``text``, or None when the donor asset is absent.

    Deep-copies the committed donor and rewrites the string in its three
    places (descriptor ``Txt``, ``Editor.Text``, both run-length arrays), the
    tracking, and the anchor transform. Photoshop's centre justification puts
    the ink ``tracking*size/2000`` px right of the anchor, so the anchor is
    pre-compensated to land the ink centred on the canvas.
    """
    donor = _load_donor_tysh()
    if donor is None:
        return None
    block = copy.deepcopy(donor)
    tysh = block.data

    tx = geo.CENTER_X - tracking * geo.LABEL_FONT_PX / 2000.0
    ty = _TYPE_BASELINE.get(label_center_y, float(label_center_y) + 11.0)
    tysh.transform = (1.0, 0.0, 0.0, 1.0, tx, ty)

    td = tysh.text_data
    td[b"Txt "].value = text + "\x00"
    engine = td[b"EngineData"].value["EngineDict"]
    engine["Editor"]["Text"].value = text + "\r"
    for run in ("StyleRun", "ParagraphRun"):
        lengths = engine[run]["RunLengthArray"]
        item = copy.deepcopy(lengths[0])
        item.value = len(text) + 1
        lengths._items[:] = [item]
    style = engine["StyleRun"]["RunArray"][0]["StyleSheet"]["StyleSheetData"]
    style["Tracking"].value = tracking

    # Ink extents (points, relative to the anchor) — hit-test box until
    # Photoshop re-shapes the text on first edit.
    half = float(ink_width) / 2.0
    for key in (b"bounds", b"boundingBox"):
        if key in td:
            td[key][b"Left"].value = -half
            td[key][b"Rght"].value = half
    return block


_DONOR_CACHE: dict = {}


def _load_donor_tysh() -> Optional[Any]:
    from psd_tools.psd.tagged_blocks import TaggedBlock

    if "tysh" in _DONOR_CACHE:
        return _DONOR_CACHE["tysh"]
    if not LABEL_TYSH_BIN.exists():
        _DONOR_CACHE["tysh"] = None  # genuine not-found: the donor is optional
        return None
    try:
        raw = LABEL_TYSH_BIN.read_bytes()
        blob = TaggedBlock.read(io.BytesIO(raw), version=1, padding=1)
        # psd-tools returns None (with only a log line) on bad bytes rather
        # than raising — normalise that to a failure.
        if blob is None or not hasattr(getattr(blob, "data", None), "text_data"):
            raise ValueError("asset is not a TySh tagged block")
    except Exception:
        # Transient failure: don't cache — retry next export.
        logging.getLogger(__name__).warning(
            "CL2K label donor %s unreadable; label falls back to raster this "
            "export",
            LABEL_TYSH_BIN,
            exc_info=True,
        )
        return None
    _DONOR_CACHE["tysh"] = blob
    return blob


def make_border_layer(psd: Any, plate: Any) -> Any:
    """The effects-only BORDER LAYER: an opaque plate whose fill is hidden
    (fill opacity 0) so only the live Stroke + Inner Glow paint."""
    from psd_tools.api.layers import PixelLayer
    from psd_tools.constants import Tag

    layer = PixelLayer.frompil(plate, psd, "BORDER LAYER")
    layer.tagged_blocks[Tag.OBJECT_BASED_EFFECTS_LAYER_INFO] = border_effects_block()
    layer.tagged_blocks.set_data(Tag.BLEND_FILL_OPACITY, 0)
    return layer


def make_gradient_layer(parent: Any) -> Any:
    """A live gradient-fill layer named as the template's BLACK GRADIENT."""
    from PIL import Image
    from psd_tools.api.layers import PixelLayer
    from psd_tools.constants import Tag

    stub = Image.new("RGBA", (1, 1), (0, 0, 0, 0))
    layer = PixelLayer.frompil(stub, parent, "BLACK GRADIENT")
    layer.tagged_blocks[Tag.GRADIENT_FILL_SETTING] = gradient_fill_block()
    # Fill layers carry no pixels — extent comes from the canvas. Zero the
    # record bbox so readers treat it as a true fill layer, not a 1x1 pixel.
    rec = layer._record
    rec.top = rec.left = rec.bottom = rec.right = 0
    return layer


def inject_preview(psd: Any, preview: Any, out: io.BytesIO) -> None:
    """Write ``psd`` with ``preview`` as the embedded flattened image.

    Bypasses ``PSDImage.save()``'s recomposite (psd-tools cannot render the
    live effects — Inner Glow is unimplemented and its stroke painter drops
    three of the four frame edges) by setting the image data directly and
    clearing the dirty flag. ``preview`` must match the document's channel
    count (RGBA here).
    """
    if preview.mode != psd.pil_mode:
        preview = preview.convert(psd.pil_mode)
    from psd_tools.constants import Compression

    # PSDImage.new leaves the image-data section RAW (6MB at this canvas).
    psd._record.image_data.compression = Compression.RLE
    psd._record.image_data.set_data(
        [channel.tobytes() for channel in preview.split()], psd._record.header
    )
    try:
        from psd_tools.constants import Resource

        info = psd.image_resources.get_data(Resource.VERSION_INFO)
        if info is not None:
            info.has_composite = True
    except (AttributeError, KeyError, ImportError):
        # VERSION_INFO is optional metadata — a reader that lacks it still
        # opens the PSD, so never fail the save over the composite flag.
        pass
    psd._updated = False
    psd.save(out)
