export const moduleOrder = [
    'general',
    'main',
    'sync_gdrive',
    'poster_renamerr',
    'poster_cleanarr',
    'plex_maintenance',
    'border_replacerr',
    'unmatched_assets',
    'renameinatorr',
    'upgradinatorr',
    'nohl',
    'nestarr',
    'labelarr',
    'health_checkarr',
    'jduparr',
];
