import datetime
from typing import Any, Dict, List, Optional

from .db_base import DatabaseBase


class Cl2kGenerated(DatabaseBase):
    """Provenance of CL2K posters generated by the cl2k_maker module."""

    def record(self, rec: Dict[str, Any]) -> None:
        """Upsert a generated-poster record (keyed on the output file path)."""
        now = datetime.datetime.now(datetime.timezone.utc).isoformat()
        self.execute_query(
            """
            INSERT INTO cl2k_generated
                (kind, tmdb_id, tvdb_id, imdb_id, season_number, title, year,
                 file, backdrop_path, logo_source, uploaded, generated_at)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            ON CONFLICT(file) DO UPDATE SET
                kind=excluded.kind, tmdb_id=excluded.tmdb_id,
                tvdb_id=excluded.tvdb_id, imdb_id=excluded.imdb_id,
                season_number=excluded.season_number, title=excluded.title,
                year=excluded.year, backdrop_path=excluded.backdrop_path,
                logo_source=excluded.logo_source, uploaded=excluded.uploaded,
                generated_at=excluded.generated_at
            """,
            (
                rec.get("kind"),
                rec.get("tmdb_id"),
                rec.get("tvdb_id"),
                rec.get("imdb_id"),
                rec.get("season_number"),
                rec.get("title"),
                rec.get("year"),
                rec.get("file"),
                rec.get("backdrop_path"),
                rec.get("logo_source"),
                int(rec.get("uploaded", 0)),
                now,
            ),
        )

    def exists_for(
        self,
        kind: str,
        tmdb_id: Optional[int],
        season_number: Optional[int] = None,
    ) -> bool:
        """True if a poster for this tmdb_id (+season) was already generated."""
        if not tmdb_id:
            return False
        if season_number is not None:
            row = self.execute_query(
                "SELECT 1 FROM cl2k_generated "
                "WHERE kind=? AND tmdb_id=? AND season_number=? LIMIT 1",
                (kind, tmdb_id, season_number),
                fetch_one=True,
            )
        else:
            row = self.execute_query(
                "SELECT 1 FROM cl2k_generated WHERE kind=? AND tmdb_id=? LIMIT 1",
                (kind, tmdb_id),
                fetch_one=True,
            )
        return row is not None

    def get_backdrop_for(self, tmdb_id: Optional[int]) -> Optional[str]:
        """Most-recent backdrop_path generated for a tmdb_id (any kind).

        Lets a new season reuse the show's existing background (DAPS: reuse the
        same backdrop across seasons, only change the season number).
        """
        if not tmdb_id:
            return None
        row = self.execute_query(
            "SELECT backdrop_path FROM cl2k_generated "
            "WHERE tmdb_id=? AND backdrop_path IS NOT NULL "
            "ORDER BY generated_at DESC LIMIT 1",
            (tmdb_id,),
            fetch_one=True,
        )
        return row["backdrop_path"] if row else None

    def list_recent(self, limit: int = 200) -> List[Dict[str, Any]]:
        return (
            self.execute_query(
                "SELECT * FROM cl2k_generated ORDER BY generated_at DESC LIMIT ?",
                (limit,),
                fetch_all=True,
            )
            or []
        )

    def mark_uploaded(self, file: str) -> None:
        self.execute_query(
            "UPDATE cl2k_generated SET uploaded=1 WHERE file=?", (file,)
        )
