name: Stale issues & PRs

on:
  schedule:
    - cron: '0 5 * * *'  # daily
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    uses: chodeus/chodeus-ops/.github/workflows/stale-issues.yml@f35f1f8b3e78542fc99e8c2b075a7685b3f5b9b9 # main
